#:schema https://mise.jdx.dev/schema/mise-task.json

["gitsubmod:remove"]
usage = '''
arg "<submodule-path>" help="submodule-path is always relative to {{ config_root }}"
'''

run = """
set -e
git submodule deinit -f "$usage_submodule_path" || true
rm -rf .git/modules/"$(basename "$usage_submodule_path")"
"""

["gitsubmod:init-llvm-project"]
raw = true
interactive = true
run = """
set -e

if [ -n "$(ls -A {{ vars.llvm_root }} 2>/dev/null)" ]; then
  printf 'submodules already exist in %s; overwrite? [y/N] ' \
    {{ vars.llvm_root }} >&2;
  read -r ans
  case "$ans" in
    [yY]*)  mise run gitsubmod:remove {{ vars.llvm_root }} ;;
    *) echo 'aborted' >&2; exit 1 ;;
  esac
fi

name=$(basename {{ vars.llvm_root }})
url=$(git config -f .gitmodules --get "submodule.$name.url")
commit=$(git ls-tree HEAD -- "{{ vars.llvm_root }}" | awk '{print $3}')

git clone --filter=blob:none --no-checkout "$url" {{ vars.llvm_root }}
git -C {{ vars.llvm_root }} sparse-checkout set --no-cone {{ vars.llvm_sparse_paths }}
git -C {{ vars.llvm_root }} checkout --quiet "$commit"
# Absorb submodule into main repository
if ! out=$(git submodule absorbgitdirs {{ vars.llvm_root }} 2>&1); then
  printf '%s\n' "$out" >&2
  exit 1
fi
git submodule init {{ vars.llvm_root }}
"""

["gitsubmod:init-inkwell"]
raw = true
interactive = true
run = '''
set -e

if [ -n "$(ls -A {{ vars.inkwell_root }})" ]; then
  printf 'submodules already exist in %s; overwrite? [y/N] ' {{ vars.inkwell_root }} >&2;
  read -r ans
  case "$ans" in
    [yY]*)  mise run gitsubmod:remove {{ vars.inkwell_root }} ;;
    *) echo 'aborted' >&2; exit 1 ;;
  esac
fi

git submodule update --init {{ vars.inkwell_root }}
'''


["gitsubmod:update-llvm-project"]
raw = true
interactive = true
description = "Sync llvm-project submodule to the remote main repository's commit"
run = '''
set -e
git submodule update --init --depth 1 --filter=blob:none {{ vars.llvm_root }}
git -C {{ vars.llvm_root }} sparse-checkout reapply
'''

["gitsubmod:update-inkwell"]
raw = true
interactive = true
run = '''
set -e
git submodule update {{ vars.inkwell_root }}
'''

["gitsubmod:update"]
depends = ["gitsubmod:update-inkwell", "gitsubmod:update-llvm-project"]

["gitsubmod:init"]
depends = ["gitsubmod:init-inkwell", "gitsubmod:init-llvm-project"]
